apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password-fetcher
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-ssm-cluster-store
    kind: ClusterSecretStore
  target:
    name: my-app-db-secret
    creationPolicy: Owner
  data:
    - secretKey: test_string
      remoteRef:
        key: /kubernetesTest/TestString