apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password-fetcher
spec:
  refreshInterval: "1h" # ESO will check AWS every hour for updates!
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: my-app-db-secret # This is the native K8s secret ESO will create
    creationPolicy: Owner
  data:
    - secretKey: test_string # The key inside the K8s secret
      remoteRef:
        key: /kubernetesTest/TestString