apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-ssm-cluster-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1 # Make sure this matches your AWS region
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret-creds
            key: access-key
            namespace: default  # <--- CRITICAL: Tells the cluster store where to find the keys
          secretAccessKeySecretRef:
            name: aws-secret-creds
            key: secret-access-key
            namespace: default  # <--- CRITICAL