apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: my-node-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster  # Links this pool to your cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: ephemeral