apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akhq
  namespace: argocd
spec:
  project: default
  source:
    chart: akhq
    repoURL: https://akhq.io/
    targetRevision: 0.24.0 # Check for latest version
    helm:
      values: |
        configuration:
          akhq:
            security:
              default-group: reader # defaulting users to read-only
            connections:
              my-cluster:
                properties:
                  bootstrap.servers: "my-cluster-kafka-bootstrap.kafka.svc:9092"
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true