apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TFWulp-Levarne/ArgoCD-example-project.git
    targetRevision: HEAD
    path: infrastructure/kafka
    directory:
      recurse: true # Important to pick up subfolders (cluster, topics)
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true