apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: strimzi-kafka-operator
    repoURL: https://strimzi.io/charts/
    targetRevision: 0.48.0  # Lock the version here
    helm:
      parameters:
        - name: watchAnyNamespace
          value: "true" # Allows it to manage Kafka clusters in any namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka # Where the operator pod itself will live
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true